### ISSUE TITLE
Get synthlisa running in standard python 2.7 environment using docker

### ISSUE THREAD

**Issue by KarstenWiesner** [vallis/synthlisa#2]
Hi all,
as we had problems to get synthlisa up and running even with python 2.7 I have build a Docker environment to get a standard environment for testing this: 

In branch docker-env:
> docker build --rm -t synthlisa-docker-env .
run the container with
> ./kickstart

at the container your are user lisa with (sudo) password lisa. Your home directory is mounted to /home/lisa/mnt. On this container I have build synth lisa with: 
> sudo python setup.py install

but on
> python examples/paper-examples/test-binary.py

I get the error:
Traceback (most recent call last):
  File "examples/paper-examples/test-binary.py", line 67, in <module>
    [alphas,betas,gammas] = transpose(getobsc(samples,stime,[signalTDI.alpha,
  File "/usr/local/lib/python2.7/dist-packages/synthlisa/lisaswig.py", line 1974, in <lambda>
    __getattr__ = lambda self, name: _swig_getattr(self, TDIsignal, name)
  File "/usr/local/lib/python2.7/dist-packages/synthlisa/lisaswig.py", line 57, in _swig_getattr
    raise AttributeError(name)
AttributeError: alpha

What is wrong?
Cheers,
Karsten

**Comment by vallis** [comment]
There may be things missing from the wrapper, but in this case I think the example script is outdated, using a naming of TDI observables that is not included anymore in the C++ code. One should replace alpha, beta, and gamma with alpham, betam, and gammam.

**Comment by KarstenWiesner** [comment]
I did this. The test started to run but then ... obviously it is missing some data ...

...completed in 5 s [52428 rows/s].
...completed in 3 s [87381 rows/s].
S/N =  0.592616112954 over T =  33554432.0  s.
Traceback (most recent call last):
  File "examples/paper-examples/test-binary.py", line 96, in <module>
    comments='EccentricInclined 1st-gen. optimal-TDI observables for 1 mHz binary')
  File "/usr/local/lib/python2.7/dist-packages/synthlisa/lisaxml.py", line 441, in __init__
    writeXML.__init__(self,self.filename)
  File "/usr/local/lib/python2.7/dist-packages/synthlisa/lisaxml.py", line 267, in __init__
    self.f = open(filename,'w')
IOError: [Errno 2] No such file or directory: 'data/binary.xml'
Exception AttributeError: "lisaXML instance has no attribute 'opened'" in <bound method lisaXML.__del__ of <synthlisa.lisaxml.lisaXML instance at 0x7f4a4da6a488>> ignored
l

**Comment by KarstenWiesner** [comment]
Simply fixed by letting test-binary.py create the /data directory
docker environment available on docker cloud: karstenwiesner/synthlisa
